defmodule Kjogvi.Legacy.Import.ChecklistsTest do
  # Not async: `Checklists.import/3` calls `setval('checklists_id_seq', ...)`, which is a
  # non-transactional, database-global side effect that the SQL sandbox cannot
  # roll back or isolate. Running concurrently with other tests that draw from
  # the same sequence caused intermittent `checklists_pkey` violations.
  use Kjogvi.DataCase, async: false

  import Kjogvi.Factory

  alias Kjogvi.Birding.Checklist
  alias Kjogvi.Legacy.Import.Checklists
  alias Kjogvi.Repo

  @columns [
    "id",
    "locus_id",
    "observ_date",
    "start_time",
    "effort_type",
    "autogenerated",
    "created_at",
    "updated_at",
    "notes",
    "weather"
  ]

  defp row(overrides) do
    defaults = %{
      "id" => 1,
      "locus_id" => nil,
      "observ_date" => "2026-01-02",
      "start_time" => "",
      "effort_type" => "stationary",
      "autogenerated" => false,
      "created_at" => "2026-01-02T03:04:05Z",
      "updated_at" => "2026-01-02T03:04:05Z",
      "notes" => "  kept  ",
      "weather" => "   "
    }

    attrs = Map.merge(defaults, overrides)
    Enum.map(@columns, &Map.fetch!(attrs, &1))
  end

  describe "import/3" do
    test "marks imported checklists with the :legacy import source" do
      user = Kjogvi.AccountsFixtures.user_fixture()
      location = insert(:location)

      Checklists.import(@columns, [row(%{"id" => 1, "locus_id" => location.id})], user: user)

      [checklist] = Repo.all(Checklist)
      assert checklist.import_source == :legacy
    end

    test "keeps the original id of imported checklists" do
      user = Kjogvi.AccountsFixtures.user_fixture()
      location = insert(:location)

      Checklists.import(@columns, [row(%{"id" => 42, "locus_id" => location.id})], user: user)

      [checklist] = Repo.all(Checklist)
      assert checklist.id == 42
    end

    test "normalizes blank text columns to nil" do
      user = Kjogvi.AccountsFixtures.user_fixture()
      location = insert(:location)

      Checklists.import(@columns, [row(%{"id" => 1, "locus_id" => location.id})], user: user)

      [checklist] = Repo.all(Checklist)
      assert checklist.notes == "kept"
      assert checklist.weather == nil
    end

    test "advances the id sequence past @min_start_seq for new checklists" do
      user = Kjogvi.AccountsFixtures.user_fixture()
      location = insert(:location)

      Checklists.import(@columns, [row(%{"id" => 42, "locus_id" => location.id})], user: user)

      next_checklist = insert(:checklist, user: user)
      assert next_checklist.id >= 20_000
    end
  end
end
