defmodule Mix.Tasks.Kjogvi.CreateAdmin do
  @shortdoc "Creates an admin user with a generated password"

  @moduledoc """
  Creates an admin user with an autogenerated password and prints it.

      mix kjogvi.create_admin [EMAIL]

  Prompts for the email unless given as an argument. To save the password
  to 1Password instead of printing it, use `bin/create_admin`, which wraps
  this task with the `op` CLI. (`op` cannot be driven from within the task:
  the BEAM detaches spawned programs from the terminal, so its interactive
  sign-in/authorization prompts would never reach the user.)
  """

  use Mix.Task

  @requirements ["app.start"]

  @impl Mix.Task
  def run(args) do
    email = List.first(args) || prompt_email()

    password = generate_password()

    case Kjogvi.Accounts.register_admin(%{email: email, password: password}) do
      {:ok, user} ->
        Mix.shell().info("Admin user #{user.email} created.")
        Mix.shell().info("Password: #{password}")

      {:error, changeset} ->
        Mix.raise("Could not create admin user:\n" <> format_errors(changeset))
    end
  end

  defp prompt_email do
    case Mix.shell().prompt("Email:") |> String.trim() do
      "" -> Mix.raise("An email is required.")
      email -> email
    end
  end

  defp generate_password do
    :crypto.strong_rand_bytes(18) |> Base.url_encode64()
  end

  defp format_errors(changeset) do
    changeset
    |> Ecto.Changeset.traverse_errors(fn {msg, opts} ->
      Regex.replace(~r/%{(\w+)}/, msg, fn _, key ->
        opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
      end)
    end)
    |> Enum.map_join("\n", fn {field, messages} ->
      "  #{field}: #{Enum.join(messages, ", ")}"
    end)
  end
end
