services:
  database:
    image: postgres:18.3-trixie
    environment:
      POSTGRES_USER: kjogvi
      POSTGRES_PASSWORD: kjogvi
      POSTGRES_DB: kjogvi_dev
    ports:
      - "5498:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U kjogvi -h 127.0.0.1 -d kjogvi_dev
      interval: 3s

# Declare the volumes that our application uses.
volumes:
  pg_data_dev:
