services:
  database:
    image: bitnami/postgresql:16-debian-12
    environment:
      POSTGRES_USER: kjogvi
      POSTGRES_PASSWORD: kjogvi
      POSTGRES_DB: kjogvi_dev
    ports:
      - "5498:5432"
    volumes:
      - pg_data16:/bitnami/postgresql
    configs:
      - source: create_ornitho_db
        target: /docker-entrypoint-initdb.d/create-ornitho-db.sql  
    healthcheck:
      test: pg_isready -U kjogvi -h 127.0.0.1
      interval: 3s

# Declare the volumes that our application uses.
volumes:
  pg_data16:

configs:
  create_ornitho_db:    
    content: |
      CREATE DATABASE ornithologue_dev WITH OWNER kjogvi;
