name: kjogvi-demo

services:
  web:
    build:
      context: .
    environment:
      SECRET_KEY_BASE: M0wBY/H0jPgHjM2ml/wTYn/HKsIopIlsvQvP3MJTXNSptX20f3BcFyjH5MtsFRJW
      DATABASE_URL: postgres://kjogvi:kjogvi@database-demo/kjogvi_prod
      PHX_PORT: 5040
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ORNITHO_IMPORTER_S3_BUCKET: ${ORNITHO_IMPORTER_S3_BUCKET}
      ORNITHO_IMPORTER_S3_REGION: ${ORNITHO_IMPORTER_S3_REGION}
      LEGACY_URL: ${LEGACY_URL}
      LEGACY_API_KEY: ${LEGACY_API_KEY}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    # env_file:
    #   - .env.docker
    # command: 
    ports:
      - "5040:4000"
    depends_on:
      database-demo:
        condition: service_healthy  

  database-demo:
    image: postgres:18.1-trixie
    environment:
      POSTGRES_USER: kjogvi
      POSTGRES_PASSWORD: kjogvi
      POSTGRES_DB: kjogvi_prod
    # ports:
    #   - "5498:5432"
    volumes:
      - pg_data-demo:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U kjogvi -h 127.0.0.1 -d kjogvi_prod
      interval: 3s

# Declare the volumes that our application uses.
volumes:
  pg_data-demo:
