services:
  web:
    build:
      context: .
    image: kjogvi-web
    environment:
      SECRET_KEY_BASE: M0wBY/H0jPgHjM2ml/wTYn/HKsIopIlsvQvP3MJTXNSptX20f3BcFyjH5MtsFRJW
      DATABASE_URL: postgres://kjogvi:kjogvi@database/kjogvi_docker
      ORNITHO_DATABASE_URL: postgres://kjogvi:kjogvi@database/ornithologue_docker
      PHX_PORT: 5040
#    env_file:
#      - .env.docker
#   command: 
    ports:
      - "5040:4000"
    depends_on:
      database:
        condition: service_healthy  

  database:
    image: bitnami/postgresql:15-debian-11
    environment:
      POSTGRES_USER: kjogvi
      POSTGRES_PASSWORD: kjogvi
      # POSTGRES_DB: kjogvi_docker
    # Temporarily to seed database
    ports:
      - "5498:5432"
    healthcheck:
      test: pg_isready -U kjogvi -h 127.0.0.1
      interval: 3s

# Declare the volumes that our application uses.
volumes: {}
  # db_data15:
