--
-- PostgreSQL database dump
--

\restrict iihZTVSKM8rnJJf7kmhS5WQaQqcJc5rTou4bLNfHd2zQhU2tYkcfVXdoXrI3rUG

-- Dumped from database version 17.9 (Debian 17.9-1.pgdg13+1)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cards (
    id bigint NOT NULL,
    observ_date date NOT NULL,
    location_id bigint NOT NULL,
    effort_type character varying(255) NOT NULL,
    start_time time(0) without time zone,
    duration_minutes integer,
    distance_kms double precision,
    area_acres double precision,
    biotope character varying(255),
    weather character varying(255),
    observers character varying(255),
    notes text,
    kml_url character varying(255),
    motorless boolean DEFAULT false NOT NULL,
    legacy_autogenerated boolean DEFAULT false NOT NULL,
    resolved boolean DEFAULT true NOT NULL,
    ebird_id character varying(255),
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    user_id bigint NOT NULL,
    cached_year integer GENERATED ALWAYS AS (EXTRACT(year FROM observ_date)) STORED,
    cached_month integer GENERATED ALWAYS AS (EXTRACT(month FROM observ_date)) STORED,
    import_source character varying(255),
    ebird_complete boolean
);


--
-- Name: cards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: cards_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.cards_id_seq OWNED BY public.cards.id;


--
-- Name: image_observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_observations (
    id bigint NOT NULL,
    image_id bigint NOT NULL,
    observation_id bigint NOT NULL,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: image_observations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.image_observations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: image_observations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.image_observations_id_seq OWNED BY public.image_observations.id;


--
-- Name: images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images (
    id bigint NOT NULL,
    token character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    title character varying(255),
    description text,
    sort_order integer DEFAULT 100 NOT NULL,
    extras jsonb DEFAULT '{}'::jsonb NOT NULL,
    file character varying(255),
    storage_backend character varying(255) DEFAULT 'local'::character varying NOT NULL,
    user_id bigint NOT NULL,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    import_source character varying(255),
    legacy_url character varying(255),
    multi_species boolean DEFAULT false NOT NULL
);


--
-- Name: images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: images_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.images_id_seq OWNED BY public.images.id;


--
-- Name: locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locations (
    id bigint NOT NULL,
    slug character varying(64) NOT NULL,
    name_en character varying(255) NOT NULL,
    location_type character varying(32) NOT NULL,
    iso_code character varying(16),
    lat numeric(8,5),
    lon numeric(8,5),
    public_index smallint,
    is_private boolean DEFAULT false NOT NULL,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    import_source character varying(255),
    extras jsonb DEFAULT '{}'::jsonb NOT NULL,
    user_id bigint,
    country_id bigint,
    subdivision1_id bigint,
    subdivision2_id bigint,
    city_id bigint,
    site_id bigint
);


--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: locations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.locations_id_seq OWNED BY public.locations.id;


--
-- Name: observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.observations (
    id bigint NOT NULL,
    card_id bigint NOT NULL,
    taxon_key character varying(255) NOT NULL,
    quantity character varying(255),
    voice boolean DEFAULT false NOT NULL,
    notes text,
    private_notes text,
    unreported boolean DEFAULT false NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    ebird_obs_id character varying(255),
    inserted_at timestamp without time zone,
    updated_at timestamp without time zone,
    import_source character varying(255)
);


--
-- Name: observations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.observations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: observations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.observations_id_seq OWNED BY public.observations.id;


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version bigint NOT NULL,
    inserted_at timestamp(0) without time zone
);


--
-- Name: special_locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.special_locations (
    id bigint NOT NULL,
    parent_location_id bigint NOT NULL,
    child_location_id bigint NOT NULL
);


--
-- Name: special_locations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.special_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: special_locations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.special_locations_id_seq OWNED BY public.special_locations.id;


--
-- Name: species_pages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.species_pages (
    id bigint NOT NULL,
    name_sci character varying(255) NOT NULL,
    common_name character varying(255),
    name_en character varying(255),
    "order" character varying(255),
    family character varying(255),
    extras jsonb DEFAULT '{}'::jsonb,
    sort_order integer NOT NULL,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: species_pages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.species_pages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: species_pages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.species_pages_id_seq OWNED BY public.species_pages.id;


--
-- Name: species_taxa_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.species_taxa_mappings (
    id bigint NOT NULL,
    species_page_id bigint NOT NULL,
    taxon_key character varying(255) NOT NULL,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: species_taxa_mappings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.species_taxa_mappings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: species_taxa_mappings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.species_taxa_mappings_id_seq OWNED BY public.species_taxa_mappings.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email public.citext NOT NULL,
    hashed_password character varying(255) NOT NULL,
    roles character varying(255)[] DEFAULT ARRAY[]::character varying[] NOT NULL,
    extras jsonb DEFAULT '{}'::jsonb,
    confirmed_at timestamp without time zone,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    default_book_signature character varying(255),
    is_main_user boolean DEFAULT false NOT NULL,
    public_token character varying(255) NOT NULL,
    nickname character varying(255) NOT NULL,
    display_name character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: users_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token bytea NOT NULL,
    context character varying(255) NOT NULL,
    sent_to character varying(255),
    inserted_at timestamp without time zone NOT NULL
);


--
-- Name: users_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_tokens_id_seq OWNED BY public.users_tokens.id;


--
-- Name: cards id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards ALTER COLUMN id SET DEFAULT nextval('public.cards_id_seq'::regclass);


--
-- Name: image_observations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_observations ALTER COLUMN id SET DEFAULT nextval('public.image_observations_id_seq'::regclass);


--
-- Name: images id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images ALTER COLUMN id SET DEFAULT nextval('public.images_id_seq'::regclass);


--
-- Name: locations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations ALTER COLUMN id SET DEFAULT nextval('public.locations_id_seq'::regclass);


--
-- Name: observations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations ALTER COLUMN id SET DEFAULT nextval('public.observations_id_seq'::regclass);


--
-- Name: special_locations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.special_locations ALTER COLUMN id SET DEFAULT nextval('public.special_locations_id_seq'::regclass);


--
-- Name: species_pages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.species_pages ALTER COLUMN id SET DEFAULT nextval('public.species_pages_id_seq'::regclass);


--
-- Name: species_taxa_mappings id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.species_taxa_mappings ALTER COLUMN id SET DEFAULT nextval('public.species_taxa_mappings_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: users_tokens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_tokens ALTER COLUMN id SET DEFAULT nextval('public.users_tokens_id_seq'::regclass);


--
-- Name: cards cards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_pkey PRIMARY KEY (id);


--
-- Name: image_observations image_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_observations
    ADD CONSTRAINT image_observations_pkey PRIMARY KEY (id);


--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: observations observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: special_locations special_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.special_locations
    ADD CONSTRAINT special_locations_pkey PRIMARY KEY (id);


--
-- Name: species_pages species_pages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.species_pages
    ADD CONSTRAINT species_pages_pkey PRIMARY KEY (id);


--
-- Name: species_taxa_mappings species_taxa_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.species_taxa_mappings
    ADD CONSTRAINT species_taxa_mappings_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_tokens users_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_tokens
    ADD CONSTRAINT users_tokens_pkey PRIMARY KEY (id);


--
-- Name: cards_cached_month_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cards_cached_month_index ON public.cards USING btree (cached_month);


--
-- Name: cards_cached_year_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cards_cached_year_index ON public.cards USING btree (cached_year);


--
-- Name: cards_ebird_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX cards_ebird_id_index ON public.cards USING btree (ebird_id) WHERE (ebird_id IS NOT NULL);


--
-- Name: cards_location_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cards_location_id_index ON public.cards USING btree (location_id);


--
-- Name: cards_observ_date_location_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cards_observ_date_location_id_index ON public.cards USING btree (observ_date, location_id);


--
-- Name: cards_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cards_user_id_index ON public.cards USING btree (user_id);


--
-- Name: image_observations_image_id_observation_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX image_observations_image_id_observation_id_index ON public.image_observations USING btree (image_id, observation_id);


--
-- Name: image_observations_observation_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX image_observations_observation_id_index ON public.image_observations USING btree (observation_id);


--
-- Name: images_token_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX images_token_index ON public.images USING btree (token);


--
-- Name: images_user_id_slug_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX images_user_id_slug_index ON public.images USING btree (user_id, slug);


--
-- Name: locations_city_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_city_id_index ON public.locations USING btree (city_id);


--
-- Name: locations_country_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_country_id_index ON public.locations USING btree (country_id);


--
-- Name: locations_location_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_location_type_index ON public.locations USING btree (location_type);


--
-- Name: locations_site_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_site_id_index ON public.locations USING btree (site_id);


--
-- Name: locations_slug_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX locations_slug_index ON public.locations USING btree (slug);


--
-- Name: locations_subdivision1_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_subdivision1_id_index ON public.locations USING btree (subdivision1_id);


--
-- Name: locations_subdivision2_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_subdivision2_id_index ON public.locations USING btree (subdivision2_id);


--
-- Name: locations_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_user_id_index ON public.locations USING btree (user_id);


--
-- Name: observations_card_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX observations_card_id_index ON public.observations USING btree (card_id);


--
-- Name: observations_taxon_key_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX observations_taxon_key_index ON public.observations USING btree (taxon_key);


--
-- Name: special_locations_parent_location_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX special_locations_parent_location_id_index ON public.special_locations USING btree (parent_location_id);


--
-- Name: species_pages_name_sci_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX species_pages_name_sci_index ON public.species_pages USING btree (name_sci);


--
-- Name: species_pages_sort_order_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX species_pages_sort_order_index ON public.species_pages USING btree (sort_order);


--
-- Name: species_taxa_mappings_species_page_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX species_taxa_mappings_species_page_id_index ON public.species_taxa_mappings USING btree (species_page_id);


--
-- Name: species_taxa_mappings_taxon_key_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX species_taxa_mappings_taxon_key_index ON public.species_taxa_mappings USING btree (taxon_key);


--
-- Name: users_default_book_signature_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_default_book_signature_index ON public.users USING btree (default_book_signature);


--
-- Name: users_email_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_email_index ON public.users USING btree (email);


--
-- Name: users_is_main_user_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_is_main_user_index ON public.users USING btree (is_main_user) WHERE is_main_user;


--
-- Name: users_nickname_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_nickname_index ON public.users USING btree (nickname);


--
-- Name: users_public_token_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_public_token_index ON public.users USING btree (public_token);


--
-- Name: users_tokens_context_token_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_tokens_context_token_index ON public.users_tokens USING btree (context, token);


--
-- Name: users_tokens_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_tokens_user_id_index ON public.users_tokens USING btree (user_id);


--
-- Name: cards cards_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE RESTRICT;


--
-- Name: cards cards_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: image_observations image_observations_image_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_observations
    ADD CONSTRAINT image_observations_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.images(id) ON DELETE CASCADE;


--
-- Name: image_observations image_observations_observation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_observations
    ADD CONSTRAINT image_observations_observation_id_fkey FOREIGN KEY (observation_id) REFERENCES public.observations(id) ON DELETE CASCADE;


--
-- Name: images images_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: locations locations_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.locations(id) ON DELETE RESTRICT;


--
-- Name: locations locations_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.locations(id) ON DELETE RESTRICT;


--
-- Name: locations locations_site_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.locations(id) ON DELETE RESTRICT;


--
-- Name: locations locations_subdivision1_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_subdivision1_id_fkey FOREIGN KEY (subdivision1_id) REFERENCES public.locations(id) ON DELETE RESTRICT;


--
-- Name: locations locations_subdivision2_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_subdivision2_id_fkey FOREIGN KEY (subdivision2_id) REFERENCES public.locations(id) ON DELETE RESTRICT;


--
-- Name: locations locations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: observations observations_card_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(id) ON DELETE RESTRICT;


--
-- Name: special_locations special_locations_child_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.special_locations
    ADD CONSTRAINT special_locations_child_location_id_fkey FOREIGN KEY (child_location_id) REFERENCES public.locations(id) ON DELETE CASCADE;


--
-- Name: special_locations special_locations_parent_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.special_locations
    ADD CONSTRAINT special_locations_parent_location_id_fkey FOREIGN KEY (parent_location_id) REFERENCES public.locations(id) ON DELETE CASCADE;


--
-- Name: species_taxa_mappings species_taxa_mappings_species_page_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.species_taxa_mappings
    ADD CONSTRAINT species_taxa_mappings_species_page_id_fkey FOREIGN KEY (species_page_id) REFERENCES public.species_pages(id) ON DELETE RESTRICT;


--
-- Name: users_tokens users_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_tokens
    ADD CONSTRAINT users_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict iihZTVSKM8rnJJf7kmhS5WQaQqcJc5rTou4bLNfHd2zQhU2tYkcfVXdoXrI3rUG

INSERT INTO public."schema_migrations" (version) VALUES (20231216191458);
INSERT INTO public."schema_migrations" (version) VALUES (20231224012458);
INSERT INTO public."schema_migrations" (version) VALUES (20240120044005);
INSERT INTO public."schema_migrations" (version) VALUES (20240627032425);
INSERT INTO public."schema_migrations" (version) VALUES (20251013044023);
INSERT INTO public."schema_migrations" (version) VALUES (20251015130047);
INSERT INTO public."schema_migrations" (version) VALUES (20260115190000);
INSERT INTO public."schema_migrations" (version) VALUES (20260410000000);
INSERT INTO public."schema_migrations" (version) VALUES (20260419120000);
INSERT INTO public."schema_migrations" (version) VALUES (20260419183659);
INSERT INTO public."schema_migrations" (version) VALUES (20260508013050);
INSERT INTO public."schema_migrations" (version) VALUES (20260509232720);
INSERT INTO public."schema_migrations" (version) VALUES (20260603121159);
INSERT INTO public."schema_migrations" (version) VALUES (20260603220042);
INSERT INTO public."schema_migrations" (version) VALUES (20260606192436);
INSERT INTO public."schema_migrations" (version) VALUES (20260607195437);
INSERT INTO public."schema_migrations" (version) VALUES (20260608025435);
INSERT INTO public."schema_migrations" (version) VALUES (20260612000000);
INSERT INTO public."schema_migrations" (version) VALUES (20260613120000);
INSERT INTO public."schema_migrations" (version) VALUES (20260615170413);
INSERT INTO public."schema_migrations" (version) VALUES (20260618000000);
INSERT INTO public."schema_migrations" (version) VALUES (20260618000100);
INSERT INTO public."schema_migrations" (version) VALUES (20260618184652);
INSERT INTO public."schema_migrations" (version) VALUES (20260619120000);
INSERT INTO public."schema_migrations" (version) VALUES (20260620000000);
INSERT INTO public."schema_migrations" (version) VALUES (20260620120000);
