--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cards (
    id bigint NOT NULL,
    observ_date date NOT NULL,
    location_id bigint NOT NULL,
    effort_type character varying(255) NOT NULL,
    start_time time(0) without time zone,
    duration_minutes integer,
    distance_kms double precision,
    area_acres double precision,
    biotope character varying(255),
    weather character varying(255),
    observers character varying(255),
    notes text,
    kml_url character varying(255),
    motorless boolean DEFAULT false NOT NULL,
    legacy_autogenerated boolean DEFAULT false NOT NULL,
    resolved boolean DEFAULT false NOT NULL,
    ebird_id character varying(255),
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: cards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: cards_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.cards_id_seq OWNED BY public.cards.id;


--
-- Name: locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locations (
    id bigint NOT NULL,
    slug character varying(64) NOT NULL,
    name_en character varying(255) NOT NULL,
    location_type character varying(32),
    ancestry bigint[],
    iso_code character varying(3),
    is_patch boolean DEFAULT false NOT NULL,
    is_5mr boolean DEFAULT false NOT NULL,
    lat numeric(8,5),
    lon numeric(8,5),
    public_index smallint,
    is_private boolean DEFAULT false NOT NULL,
    cached_public_location_id bigint,
    cached_country_id bigint,
    cached_parent_id bigint,
    cached_city_id bigint,
    cached_subdivision_id bigint,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: locations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.locations_id_seq OWNED BY public.locations.id;


--
-- Name: observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.observations (
    id bigint NOT NULL,
    card_id bigint NOT NULL,
    taxon_key character varying(255) NOT NULL,
    quantity character varying(255),
    voice boolean DEFAULT false NOT NULL,
    notes text,
    private_notes text,
    unreported boolean DEFAULT false NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    ebird_obs_id character varying(255),
    inserted_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: observations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.observations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: observations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.observations_id_seq OWNED BY public.observations.id;


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version bigint NOT NULL,
    inserted_at timestamp(0) without time zone
);


--
-- Name: special_locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.special_locations (
    id bigint NOT NULL,
    parent_location_id bigint NOT NULL,
    child_location_id bigint NOT NULL
);


--
-- Name: special_locations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.special_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: special_locations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.special_locations_id_seq OWNED BY public.special_locations.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email public.citext NOT NULL,
    hashed_password character varying(255) NOT NULL,
    roles character varying(255)[] DEFAULT ARRAY[]::character varying[],
    extras jsonb DEFAULT '{}'::jsonb,
    confirmed_at timestamp without time zone,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: users_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token bytea NOT NULL,
    context character varying(255) NOT NULL,
    sent_to character varying(255),
    inserted_at timestamp without time zone NOT NULL
);


--
-- Name: users_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_tokens_id_seq OWNED BY public.users_tokens.id;


--
-- Name: cards id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards ALTER COLUMN id SET DEFAULT nextval('public.cards_id_seq'::regclass);


--
-- Name: locations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations ALTER COLUMN id SET DEFAULT nextval('public.locations_id_seq'::regclass);


--
-- Name: observations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations ALTER COLUMN id SET DEFAULT nextval('public.observations_id_seq'::regclass);


--
-- Name: special_locations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.special_locations ALTER COLUMN id SET DEFAULT nextval('public.special_locations_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: users_tokens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_tokens ALTER COLUMN id SET DEFAULT nextval('public.users_tokens_id_seq'::regclass);


--
-- Name: cards cards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: observations observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: special_locations special_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.special_locations
    ADD CONSTRAINT special_locations_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_tokens users_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_tokens
    ADD CONSTRAINT users_tokens_pkey PRIMARY KEY (id);


--
-- Name: cards_ebird_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX cards_ebird_id_index ON public.cards USING btree (ebird_id) WHERE (ebird_id IS NOT NULL);


--
-- Name: cards_location_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cards_location_id_index ON public.cards USING btree (location_id);


--
-- Name: cards_observ_date_location_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cards_observ_date_location_id_index ON public.cards USING btree (observ_date, location_id);


--
-- Name: cards_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cards_user_id_index ON public.cards USING btree (user_id);


--
-- Name: locations_ancestry_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_ancestry_index ON public.locations USING gin (ancestry);


--
-- Name: locations_cached_country_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_cached_country_id_index ON public.locations USING btree (cached_country_id) WHERE (cached_country_id IS NOT NULL);


--
-- Name: locations_location_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX locations_location_type_index ON public.locations USING btree (location_type) WHERE (location_type IS NOT NULL);


--
-- Name: locations_slug_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX locations_slug_index ON public.locations USING btree (slug);


--
-- Name: observations_card_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX observations_card_id_index ON public.observations USING btree (card_id);


--
-- Name: observations_taxon_key_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX observations_taxon_key_index ON public.observations USING btree (taxon_key);


--
-- Name: special_locations_parent_location_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX special_locations_parent_location_id_index ON public.special_locations USING btree (parent_location_id);


--
-- Name: users_email_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_email_index ON public.users USING btree (email);


--
-- Name: users_tokens_context_token_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_tokens_context_token_index ON public.users_tokens USING btree (context, token);


--
-- Name: users_tokens_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_tokens_user_id_index ON public.users_tokens USING btree (user_id);


--
-- Name: cards cards_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE RESTRICT;


--
-- Name: cards cards_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: locations locations_cached_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_cached_city_id_fkey FOREIGN KEY (cached_city_id) REFERENCES public.locations(id) ON DELETE SET NULL;


--
-- Name: locations locations_cached_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_cached_country_id_fkey FOREIGN KEY (cached_country_id) REFERENCES public.locations(id) ON DELETE RESTRICT;


--
-- Name: locations locations_cached_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_cached_parent_id_fkey FOREIGN KEY (cached_parent_id) REFERENCES public.locations(id) ON DELETE SET NULL;


--
-- Name: locations locations_cached_public_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_cached_public_location_id_fkey FOREIGN KEY (cached_public_location_id) REFERENCES public.locations(id) ON DELETE SET NULL;


--
-- Name: locations locations_cached_subdivision_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_cached_subdivision_id_fkey FOREIGN KEY (cached_subdivision_id) REFERENCES public.locations(id) ON DELETE SET NULL;


--
-- Name: observations observations_card_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(id) ON DELETE RESTRICT;


--
-- Name: special_locations special_locations_child_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.special_locations
    ADD CONSTRAINT special_locations_child_location_id_fkey FOREIGN KEY (child_location_id) REFERENCES public.locations(id) ON DELETE CASCADE;


--
-- Name: special_locations special_locations_parent_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.special_locations
    ADD CONSTRAINT special_locations_parent_location_id_fkey FOREIGN KEY (parent_location_id) REFERENCES public.locations(id) ON DELETE CASCADE;


--
-- Name: users_tokens users_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_tokens
    ADD CONSTRAINT users_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

INSERT INTO public."schema_migrations" (version) VALUES (20231216191458);
INSERT INTO public."schema_migrations" (version) VALUES (20231224012458);
INSERT INTO public."schema_migrations" (version) VALUES (20240120044005);
INSERT INTO public."schema_migrations" (version) VALUES (20240627032425);
