defmodule Kjogvi.Legacy.Import.Checklists do
  @moduledoc false

  alias Kjogvi.Legacy.Import.Utils

  @blank_to_nil_columns [:biotope, :weather, :observers, :notes, :kml_url, :ebird_id]

  @min_start_seq 100_000

  def import(columns_str, rows, opts) do
    columns = columns_str |> Enum.map(&String.to_atom/1)
    user_id = opts[:user].id

    checklists =
      for row <- rows do
        Enum.zip([:user_id | columns], [user_id | row])
        |> Map.new()
        |> transform_keys
      end

    with {_, _} <- Kjogvi.Repo.insert_all(Kjogvi.Birding.Checklist, checklists),
         {:ok, _} <-
           Kjogvi.Repo.query(
             "SELECT setval('checklists_id_seq', GREATEST(#{@min_start_seq}, (SELECT COALESCE(MAX(id), 0) FROM checklists)));"
           ) do
      :ok
    end
  end

  def cleanup do
    Kjogvi.Repo.query("DELETE FROM checklists WHERE import_source='legacy';")
  end

  defp transform_keys(
         %{
           locus_id: loc_id,
           autogenerated: autogenerated,
           created_at: created_at,
           updated_at: updated_at,
           start_time: start_time,
           observ_date: observ_date
         } = checklist
       ) do
    inserted_at = Utils.convert_timestamp(created_at)
    update_time = Utils.convert_timestamp(updated_at)
    observ_date = convert_date(observ_date)

    checklist
    |> Map.drop([:locus_id, :autogenerated, :created_at, :post_core_id])
    |> Map.put(:location_id, loc_id)
    |> Map.put(:legacy_autogenerated, autogenerated)
    |> Map.put(:inserted_at, inserted_at)
    |> Map.put(:updated_at, update_time)
    |> Map.put(:observ_date, observ_date)
    |> Map.put(:start_time, convert_start_time(start_time))
    |> Map.put(:import_source, :legacy)
    |> normalize_text_columns()
  end

  defp normalize_text_columns(checklist) do
    Enum.reduce(@blank_to_nil_columns, checklist, fn key, acc ->
      case acc do
        %{^key => value} -> Map.put(acc, key, Utils.blank_to_nil(value))
        _ -> acc
      end
    end)
  end

  def convert_start_time(""), do: nil
  def convert_start_time(nil), do: nil

  def convert_start_time(str) do
    [hr, min] = String.split(str, ":")
    {:ok, time} = Time.new(String.to_integer(hr), String.to_integer(min), 0)
    time
  end

  defp convert_date(%Date{} = date) do
    date
  end

  defp convert_date(date) when is_binary(date) do
    {:ok, converted} = Date.from_iso8601(date)
    converted
  end
end
