defmodule Kjogvi.Birding do
  @moduledoc """
  Birding related functionality (cards, observations).
  """

  import Ecto.Query

  alias Kjogvi.Repo
  alias Kjogvi.Pages.Species

  alias __MODULE__.Observation
  alias __MODULE__.Card
  alias __MODULE__.CardSearch

  @doc """
  Searches a user's cards with a `CardSearch.Filter`, paginated.

  See `Kjogvi.Birding.CardSearch.search/3`.
  """
  defdelegate search_cards(user, filter, pagination), to: CardSearch, as: :search

  def get_cards(user, %{page: page, page_size: page_size}) do
    Card
    |> Card.Query.as_card()
    |> Card.Query.by_user(user)
    |> order_by([{:desc, :observ_date}, {:desc, :id}])
    |> preload(location: [:cached_parent, :cached_city, :cached_subdivision, :cached_country])
    |> Card.Query.load_observation_count()
    |> Repo.paginate(page: page, page_size: page_size)
  end

  def fetch_card_with_observations(user, id) do
    Card
    |> Card.Query.as_card()
    |> Card.Query.by_user(user)
    |> preload(location: [:cached_parent, :cached_city, :cached_subdivision, :cached_country])
    |> Repo.get!(id)
    |> Repo.preload(observations: from(obs in Observation, order_by: obs.id))
    |> then(fn card ->
      Map.replace(
        card,
        :observations,
        card.observations |> Kjogvi.Birding.preload_taxa_and_species()
      )
    end)
  end

  def fetch_card_for_edit(user, id) do
    Card
    |> Card.Query.as_card()
    |> Card.Query.by_user(user)
    |> preload(location: [:cached_parent, :cached_city, :cached_subdivision, :cached_country])
    |> Repo.get!(id)
    |> Repo.preload(observations: from(obs in Observation, order_by: obs.id))
  end

  def preload_taxa_and_species(observations) do
    taxa =
      for obs <- observations, uniq: true do
        obs.taxon_key
      end
      |> Ornithologue.get_taxa_and_species()

    for obs <- observations do
      taxon = taxa[obs.taxon_key]
      %{obs | taxon: taxon, species: Ornitho.Schema.Taxon.species(taxon) |> Species.from_taxon()}
    end
  end

  def find_new_checklists(user, checklists) do
    new_ebird_ids =
      Card
      |> Card.Query.as_card()
      |> Card.Query.by_user(user)
      |> Card.Query.find_new_checklists(Enum.map(checklists, & &1.ebird_id))
      |> Repo.all()

    Enum.filter(checklists, &(&1.ebird_id in new_ebird_ids))
  end

  def create_card(user, attrs) do
    attrs = Map.put(attrs, "user_id", user.id)

    %Card{}
    |> Card.changeset(attrs)
    |> Repo.insert()
    |> tap_invalidate_logbook_cache(user.id)
  end

  def update_card(card, attrs) do
    card
    |> Card.changeset(attrs)
    |> Repo.update()
    |> tap_invalidate_logbook_cache(card.user_id)
  end

  @doc """
  Deletes a card, but only when it has no observations.

  Returns `{:ok, card}` on success, or `{:error, :has_observations}` when the
  card still has observations and therefore must not be deleted.
  """
  def delete_card(%Card{} = card) do
    if card_deletable?(card) do
      card
      |> Repo.delete()
      |> tap_invalidate_logbook_cache(card.user_id)
    else
      {:error, :has_observations}
    end
  end

  @doc """
  Returns `true` when a card may be deleted, i.e. it has no observations.

  Relies on the card's `observation_count` virtual field when loaded (see
  `Card.Query.load_observation_count/1`), otherwise falls back to counting
  observations in the database.
  """
  def card_deletable?(%Card{observation_count: count}) when is_integer(count) do
    count == 0
  end

  def card_deletable?(%Card{observations: observations}) when is_list(observations) do
    observations == []
  end

  def card_deletable?(%Card{id: id}) do
    not Repo.exists?(from(obs in Observation, where: obs.card_id == ^id))
  end

  defp tap_invalidate_logbook_cache({:ok, _} = result, user_id) do
    Kjogvi.Birding.Logbook.Cache.invalidate(user_id)
    result
  end

  defp tap_invalidate_logbook_cache(other, _user_id), do: other

  def new_card(user) do
    %Card{
      user_id: user.id,
      observ_date: next_empty_date(user),
      effort_type: "INCIDENTAL",
      motorless: false,
      legacy_autogenerated: false,
      resolved: false,
      observations: []
    }
  end

  @doc """
  Returns a suggested date for a new card: the day after the user's latest
  card, capped at today. Returns today when the user has no cards.
  """
  def next_empty_date(user) do
    latest_date =
      Card
      |> Card.Query.as_card()
      |> Card.Query.by_user(user)
      |> select([card: c], max(c.observ_date))
      |> Repo.one()

    today = Date.utc_today()

    case latest_date do
      nil ->
        today

      date ->
        candidate = Date.add(date, 1)
        if Date.compare(candidate, today) == :gt, do: today, else: candidate
    end
  end

  def new_observation() do
    %Observation{
      voice: false,
      hidden: false,
      unreported: false
    }
  end

  def change_card(card, attrs \\ %{}) do
    Card.changeset(card, attrs)
  end
end
