defmodule Kjogvi.Repo.Migrations.CreateCards do
  use Ecto.Migration

  # Not restricting strings length, because as per PostgreSQL documentation, there is
  # no performance gain from this: https://www.postgresql.org/docs/15/datatype-character.html

  def change do
    create table(:cards) do
      add :observ_date, :date, null: false
      add :location_id, references("locations", on_delete: :restrict), null: false

      add :effort_type, :string, null: false
      add :start_time, :time
      add :duration_minutes, :integer
      add :distance_kms, :float
      add :area_acres, :float

      add :biotope, :string
      add :weather, :string
      add :observers, :string

      add :notes, :text
      add :kml_url, :string
      add :motorless, :boolean, default: false, null: false

      add :legacy_autogenerated, :boolean, default: false, null: false
      add :resolved, :boolean, default: false, null: false

      add :ebird_id, :string

      timestamps()
    end

    create index(:cards, [:observ_date, :location_id])
    create index(:cards, :location_id)
    create index(:cards, :ebird_id, unique: true, where: "(ebird_id IS NOT NULL)")
  end
end
