defmodule Kjogvi.Birding.Card do
  @moduledoc """
  Card schema (equivalent to eBird checklist).
  """

  use Kjogvi.Schema
  import Ecto.Changeset

  @effort_types [
    "INCIDENTAL",
    "STATIONARY",
    "TRAVEL",
    "AREA",
    "HISTORICAL"
  ]

  def effort_types, do: @effort_types

  schema "cards" do
    field :observ_date, :date
    belongs_to(:location, Kjogvi.Geo.Location)

    field :effort_type, :string
    field :start_time, :time
    field :duration_minutes, :integer
    field :distance_kms, :float
    field :area_acres, :float

    field :biotope, :string
    field :weather, :string
    field :observers, :string

    field :notes, :string
    field :kml_url, :string
    field :motorless, :boolean, default: false

    field :legacy_autogenerated, :boolean, default: false
    field :resolved, :boolean, default: false

    field :ebird_id, :string

    has_many(:observations, Kjogvi.Birding.Observation, on_replace: :delete)
    belongs_to(:user, Kjogvi.Users.User)

    # Generated
    field :cached_year, :integer
    field :cached_month, :integer

    timestamps()

    field :observation_count, :integer, virtual: true
  end

  @doc false
  def changeset(card, attrs) do
    card
    |> cast(attrs |> filter_blank_observations(), [
      :observ_date,
      :location_id,
      :effort_type,
      :start_time,
      :duration_minutes,
      :distance_kms,
      :area_acres,
      :biotope,
      :weather,
      :observers,
      :notes,
      :kml_url,
      :motorless,
      :legacy_autogenerated,
      :resolved,
      :user_id
    ])
    |> validate_required([
      :observ_date,
      :location_id,
      :effort_type
    ])
    |> cast_assoc(:observations,
      with: &Kjogvi.Birding.Observation.changeset/2,
      sort_param: :observations_order,
      drop_param: :observations_drop
    )
  end

  # Remove observation entries where no meaningful fields are filled in,
  # so that empty rows added via "Add Observation" don't cause validation errors.
  defp filter_blank_observations(%{"observations" => obs} = attrs) when is_map(obs) do
    blank_indices =
      for {idx, params} <- obs, blank_observation?(params), do: idx

    filtered_obs = Map.drop(obs, blank_indices)

    attrs = %{attrs | "observations" => filtered_obs}

    case Map.get(attrs, "observations_order") do
      list when is_list(list) ->
        blank_set = MapSet.new(blank_indices)
        %{attrs | "observations_order" => Enum.reject(list, &MapSet.member?(blank_set, &1))}

      _ ->
        attrs
    end
  end

  defp filter_blank_observations(attrs), do: attrs

  defp blank_observation?(params) do
    blank?(params["taxon_key"]) &&
      blank?(params["quantity"]) &&
      blank?(params["notes"]) &&
      blank?(params["private_notes"])
  end

  defp blank?(nil), do: true
  defp blank?(""), do: true
  defp blank?(_), do: false
end
