defmodule Kjogvi.BirdingFixtures do
  @moduledoc """
  This module defines test helpers for creating
  entities via the `Kjogvi.Birding` context.
  """

  alias Kjogvi.Birding.Card
  alias Kjogvi.Repo
  alias Kjogvi.UsersFixtures

  def valid_card_attributes(attrs \\ %{}) do
    user = attrs[:user] || UsersFixtures.user_fixture()

    Enum.into(attrs, %{
      user_id: user.id,
      observ_date: Date.utc_today(),
      effort_type: "STATIONARY",
      start_time: ~T[08:00:00],
      duration_minutes: 30,
      motorless: false,
      legacy_autogenerated: false,
      resolved: false,
      observations: []
    })
  end

  def card_fixture(attrs \\ %{}) do
    {:ok, card} =
      attrs
      |> valid_card_attributes()
      |> then(&Repo.insert(%Card{} |> Card.changeset(&1)))

    card
  end
end
