defmodule Kjogvi.BirdingFixtures do
  @moduledoc """
  This module defines test helpers for creating
  entities via the `Kjogvi.Birding` context.
  """

  alias Kjogvi.Birding.Checklist
  alias Kjogvi.Repo
  alias Kjogvi.AccountsFixtures

  def valid_checklist_attributes(attrs \\ %{}) do
    user = attrs[:user] || AccountsFixtures.user_fixture()

    Enum.into(attrs, %{
      user_id: user.id,
      observ_date: Date.utc_today(),
      effort_type: "STATIONARY",
      start_time: ~T[08:00:00],
      duration_minutes: 30,
      motorless: false,
      legacy_autogenerated: false,
      resolved: false,
      observations: []
    })
  end

  def checklist_fixture(attrs \\ %{}) do
    {:ok, checklist} =
      attrs
      |> valid_checklist_attributes()
      |> then(&Repo.insert(%Checklist{} |> Checklist.changeset(&1)))

    checklist
  end
end
