name: "CI Pipeline"
on:
  push:
  pull_request:
jobs:
  tests:
    name: "Tests"
    uses: ./.github/workflows/tests.yml

  lint:
    name: "Lint"
    uses: ./.github/workflows/lint.yml

  build_image:
    name: "Docker image"
    uses: ./.github/workflows/build.yml
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
    needs:
      - tests
      - lint
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/image-bump/')
